"""autogenerated by genpy from fastfiz_msgs/ShotParams.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ShotParams(genpy.Message):
  _md5sum = "b6d6d9dab06ce45ce5fc4f7c44a44a44"
  _type = "fastfiz_msgs/ShotParams"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 a     # The x-coordinate of the cue stick (right/left english) on the CUE ball in mm. 
float64 b     # The y-coordinate of the cue stick (top/bottom english) on the CUE ball in mm. 
float64 theta # The elevation of the cue stick in degrees. 
float64 phi   # The azumith angle (heading) of the cue stick in degrees. 
float64 v     # The velocity of the cue stick before impact in m/s (max is 4.5 m/s). 
"""
  __slots__ = ['a','b','theta','phi','v']
  _slot_types = ['float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a,b,theta,phi,v

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShotParams, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.a is None:
        self.a = 0.
      if self.b is None:
        self.b = 0.
      if self.theta is None:
        self.theta = 0.
      if self.phi is None:
        self.phi = 0.
      if self.v is None:
        self.v = 0.
    else:
      self.a = 0.
      self.b = 0.
      self.theta = 0.
      self.phi = 0.
      self.v = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.a, _x.b, _x.theta, _x.phi, _x.v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.a, _x.b, _x.theta, _x.phi, _x.v,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.a, _x.b, _x.theta, _x.phi, _x.v))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.a, _x.b, _x.theta, _x.phi, _x.v,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5d = struct.Struct("<5d")
