float64 a     # The x-coordinate of the cue stick (right/left english) on the CUE ball in mm. 
float64 b     # The y-coordinate of the cue stick (top/bottom english) on the CUE ball in mm. 
float64 theta # The elevation of the cue stick in degrees. 
float64 phi   # The azumith angle (heading) of the cue stick in degrees. 
float64 v     # The velocity of the cue stick before impact in m/s (max is 4.5 m/s). 