"""autogenerated by genpy from billiards_msgs/ShotPlan.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import billiards_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class ShotPlan(genpy.Message):
  _md5sum = "2fae0f577b78b1457b53c10daefbd54e"
  _type = "billiards_msgs/ShotPlan"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# describes plan for a single shot
BallState ball
geometry_msgs/PoseStamped base_pose                     # where PR2 should "stand"
geometry_msgs/PoseStamped bridge_pose                   # where to put the bridge
                                                        # orientation is: x-forward (towards cue ball)
                                                        #                 z-(up)
                                                        #                 y-robot left
float64                   velocity                      # not used for now


================================================================================
MSG: billiards_msgs/BallState
int8                  id                  # id of the ball
                                          # 0-cue ball, 1-15 for each of the 15 balls
bool                  pocketed            # false if ball is on the table
geometry_msgs/PointStamped   point        # location of each ball
int8                  group_id            # if we want to group the ball

================================================================================
MSG: geometry_msgs/PointStamped
# This represents a Point with reference coordinate frame and timestamp
Header header
Point point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['ball','base_pose','bridge_pose','velocity']
  _slot_types = ['billiards_msgs/BallState','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ball,base_pose,bridge_pose,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShotPlan, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ball is None:
        self.ball = billiards_msgs.msg.BallState()
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
      if self.bridge_pose is None:
        self.bridge_pose = geometry_msgs.msg.PoseStamped()
      if self.velocity is None:
        self.velocity = 0.
    else:
      self.ball = billiards_msgs.msg.BallState()
      self.base_pose = geometry_msgs.msg.PoseStamped()
      self.bridge_pose = geometry_msgs.msg.PoseStamped()
      self.velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_bB3I.pack(_x.ball.id, _x.ball.pocketed, _x.ball.point.header.seq, _x.ball.point.header.stamp.secs, _x.ball.point.header.stamp.nsecs))
      _x = self.ball.point.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3db3I.pack(_x.ball.point.point.x, _x.ball.point.point.y, _x.ball.point.point.z, _x.ball.group_id, _x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs))
      _x = self.base_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w, _x.bridge_pose.header.seq, _x.bridge_pose.header.stamp.secs, _x.bridge_pose.header.stamp.nsecs))
      _x = self.bridge_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8d.pack(_x.bridge_pose.pose.position.x, _x.bridge_pose.pose.position.y, _x.bridge_pose.pose.position.z, _x.bridge_pose.pose.orientation.x, _x.bridge_pose.pose.orientation.y, _x.bridge_pose.pose.orientation.z, _x.bridge_pose.pose.orientation.w, _x.velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ball is None:
        self.ball = billiards_msgs.msg.BallState()
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
      if self.bridge_pose is None:
        self.bridge_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.ball.id, _x.ball.pocketed, _x.ball.point.header.seq, _x.ball.point.header.stamp.secs, _x.ball.point.header.stamp.nsecs,) = _struct_bB3I.unpack(str[start:end])
      self.ball.pocketed = bool(self.ball.pocketed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ball.point.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ball.point.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.ball.point.point.x, _x.ball.point.point.y, _x.ball.point.point.z, _x.ball.group_id, _x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs,) = _struct_3db3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.base_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w, _x.bridge_pose.header.seq, _x.bridge_pose.header.stamp.secs, _x.bridge_pose.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bridge_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.bridge_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.bridge_pose.pose.position.x, _x.bridge_pose.pose.position.y, _x.bridge_pose.pose.position.z, _x.bridge_pose.pose.orientation.x, _x.bridge_pose.pose.orientation.y, _x.bridge_pose.pose.orientation.z, _x.bridge_pose.pose.orientation.w, _x.velocity,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_bB3I.pack(_x.ball.id, _x.ball.pocketed, _x.ball.point.header.seq, _x.ball.point.header.stamp.secs, _x.ball.point.header.stamp.nsecs))
      _x = self.ball.point.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3db3I.pack(_x.ball.point.point.x, _x.ball.point.point.y, _x.ball.point.point.z, _x.ball.group_id, _x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs))
      _x = self.base_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w, _x.bridge_pose.header.seq, _x.bridge_pose.header.stamp.secs, _x.bridge_pose.header.stamp.nsecs))
      _x = self.bridge_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8d.pack(_x.bridge_pose.pose.position.x, _x.bridge_pose.pose.position.y, _x.bridge_pose.pose.position.z, _x.bridge_pose.pose.orientation.x, _x.bridge_pose.pose.orientation.y, _x.bridge_pose.pose.orientation.z, _x.bridge_pose.pose.orientation.w, _x.velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ball is None:
        self.ball = billiards_msgs.msg.BallState()
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
      if self.bridge_pose is None:
        self.bridge_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.ball.id, _x.ball.pocketed, _x.ball.point.header.seq, _x.ball.point.header.stamp.secs, _x.ball.point.header.stamp.nsecs,) = _struct_bB3I.unpack(str[start:end])
      self.ball.pocketed = bool(self.ball.pocketed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ball.point.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ball.point.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.ball.point.point.x, _x.ball.point.point.y, _x.ball.point.point.z, _x.ball.group_id, _x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs,) = _struct_3db3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.base_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w, _x.bridge_pose.header.seq, _x.bridge_pose.header.stamp.secs, _x.bridge_pose.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bridge_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.bridge_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.bridge_pose.pose.position.x, _x.bridge_pose.pose.position.y, _x.bridge_pose.pose.position.z, _x.bridge_pose.pose.orientation.x, _x.bridge_pose.pose.orientation.y, _x.bridge_pose.pose.orientation.z, _x.bridge_pose.pose.orientation.w, _x.velocity,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_bB3I = struct.Struct("<bB3I")
_struct_3db3I = struct.Struct("<3db3I")
_struct_7d3I = struct.Struct("<7d3I")
_struct_8d = struct.Struct("<8d")
